-- MySQL Script generated by MySQL Workbench
-- Wed Apr  7 08:47:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `CAR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CAR` ;

CREATE TABLE IF NOT EXISTS `CAR` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `manufact` VARCHAR(20) NOT NULL,
  `model` VARCHAR(20) NOT NULL,
  `year` YEAR NOT NULL,
  `COLOR` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Coches por factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Coches por factura` ;

CREATE TABLE IF NOT EXISTS `Coches por factura` (
  `CAR_id` INT NOT NULL,
  `invoice_id` INT NOT NULL,
  PRIMARY KEY (`CAR_id`, `invoice_id`),
  INDEX `fk_CAR_has_invoice_CAR1_idx` (`CAR_id` ASC) VISIBLE,
  INDEX `fk_Coches por factura_invoice1_idx` (`invoice_id` ASC) VISIBLE,
  CONSTRAINT `fk_CAR_has_invoice_CAR1`
    FOREIGN KEY (`CAR_id`)
    REFERENCES `CAR` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Coches por factura_invoice1`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `invoice` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `customer` ;

CREATE TABLE IF NOT EXISTS `customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(12) NOT NULL DEFAULT '+34',
  `email` VARCHAR(30) NULL,
  `addres` VARCHAR(50) NULL,
  `city` VARCHAR(30) NULL,
  `satate_province` VARCHAR(12) NULL,
  `country` VARCHAR(12) NULL DEFAULT 'SPAIN',
  `zip` CHAR(5) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invoice` ;

CREATE TABLE IF NOT EXISTS `invoice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `sales person` INT NOT NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_invoice_seller1_idx` (`sales person` ASC) VISIBLE,
  INDEX `fk_invoice_customer1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_invoice_seller1`
    FOREIGN KEY (`sales person`)
    REFERENCES `seller` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seller` ;

CREATE TABLE IF NOT EXISTS `seller` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `store` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
