-- MySQL Script generated by MySQL Workbench
-- Tue Apr  6 17:10:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `CAR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CAR` ;

CREATE TABLE IF NOT EXISTS `CAR` (
  `vin` INT NOT NULL AUTO_INCREMENT,
  `manufact` VARCHAR(20) NULL DEFAULT NULL,
  `model` VARCHAR(20) NULL DEFAULT NULL,
  `year` VARCHAR(45) NULL DEFAULT NULL,
  `COLOR` CHAR(6) NULL DEFAULT NULL,
  PRIMARY KEY (`vin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `customer` ;

CREATE TABLE IF NOT EXISTS `customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(12) NOT NULL DEFAULT '+34',
  `email` VARCHAR(30) NULL DEFAULT NULL,
  `addres` VARCHAR(50) NULL DEFAULT NULL,
  `city` VARCHAR(30) NULL DEFAULT NULL,
  `satate_province` VARCHAR(12) NULL DEFAULT NULL,
  `country` VARCHAR(12) NULL DEFAULT 'SPAIN',
  `zip` CHAR(5) NULL DEFAULT NULL,
  `invoice_invoice_number` INT NOT NULL,
  `invoice_CAR_vin` INT NOT NULL,
  PRIMARY KEY (`customer_id`),
  INDEX `fk_customer_invoice_idx` (`invoice_invoice_number` ASC, `invoice_CAR_vin` ASC) VISIBLE,
  CONSTRAINT `fk_customer_invoice`
    FOREIGN KEY (`invoice_invoice_number` , `invoice_CAR_vin`)
    REFERENCES `invoice` (`invoice_number` , `CAR_vin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invoice` ;

CREATE TABLE IF NOT EXISTS `invoice` (
  `invoice_number` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `car1_id` INT NOT NULL,
  `staff_id_copy1` INT NOT NULL,
  `customer_id` INT NULL DEFAULT NULL,
  `staff_id` INT NOT NULL,
  `CAR_vin` INT NOT NULL,
  `CAR_vin1` INT NOT NULL,
  PRIMARY KEY (`invoice_number`, `CAR_vin`),
  INDEX `fk_invoice_CAR1_idx` (`CAR_vin1` ASC) VISIBLE,
  CONSTRAINT `fk_invoice_CAR1`
    FOREIGN KEY (`CAR_vin1`)
    REFERENCES `CAR` (`vin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seller` ;

CREATE TABLE IF NOT EXISTS `seller` (
  `staff_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `store` INT NOT NULL,
  `CAR_vin` INT NOT NULL,
  PRIMARY KEY (`staff_id`, `CAR_vin`),
  INDEX `fk_seller_CAR1_idx` (`CAR_vin` ASC) VISIBLE,
  CONSTRAINT `fk_seller_CAR1`
    FOREIGN KEY (`CAR_vin`)
    REFERENCES `CAR` (`vin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
